### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by vfonic** [juliencrn/usehooks.ts#26]
This great repo sounds like a great candidate for publishing on npm for easier updating and security auditing. If someone knows how to set it up, it could also support tree shaking, since each of the hooks is in its own file.

What do you think?

**Comment by bclermont** [comment]
That is actualy the only reason I'm not using this project

**Comment by juliencrn** [comment]
Thanks for the feedback guys. 
I think there are very good packages for hooks, well tested and with a ton of hooks (e.g. [`react-use`](https://github.com/streamich/react-use)).

So, my initial goal here wasn't do the same, but just giving some simple code as well for understanding purpose and to speed development too.
My opinion is if I only need a pair of hooks, I prefer copy/paste there from a confidence source and keeping things simple. 

I'm not a huge fan of packaging everything (cf: [`is-odd`](https://www.npmjs.com/package/is-odd) seems like a joke).

If you want to package some hooks from this project, here or somewhere else, feel free to do what you want.

The truth, I'm not really closed to package it, it may be a good idea too. I will consider it 👍

**Comment by vfonic** [comment]
To be fair to, [now archived](https://github.com/i-voted-for-trump/is-odd), is-odd package from 2014, copy-pasting code snippets in 2021 seems like a joke. What if you realize there's a bug in one of the hooks? What's easier: copy-pasting the new code snippet hook in every project that uses that hook or updating the package via npm? How would you inform the other developers, users of the hook with a bug that there's a bug? Should they check this repo regularly? Isn't there a faster way to check for updates?

What's faster?

1. `npm i useHooks.ts`
2. Switch to editor
3. `import { useBoolean } from 'useHooks.ts'`
4. Use the hook

or 

1. Open GitHub (if you're lucky enough, you'll have this repo bookmarked or have it locally so you'll `cd` into it)
2. Open `useBoolean.ts` file (either on GitHub or locally)
3. Select all, copy
4. Switch back to main project
5. File new => useBoolean.ts => make sure it's in the right directory
6. Paste

+ Snyk checks your dependencies and your own code for any security vulnerabilities, and there are probably more reasons you could think of.

Sorry for mini rant. I thought that since you put so much effort in creating all these hooks and the documentation website, it's such a shame that people like myself and @bclermont and others don't get to use it because of the last 1% needed to publish this. If you've never published a package this is a great opportunity to experience the whole process.

**Comment by juliencrn** [comment]
Thank you mate, you're right. I will do it

**Comment by vfonic** [comment]
You sir are a legend! 🚀 
Thanks for the great work you've put into this!

**Comment by juliencrn** [comment]
Oh man, good catch, thanks! 👏

**Comment by bclermont** [comment]
As this issue had been closed, where is the package?

**Comment by juliencrn** [comment]
I re-open the issue as long as the branch isn't merged on master. It's coming soon

**Comment by juliencrn** [comment]
It's early stage, but it's now available on npm!
