### ISSUE TITLE
does useIsMounted need to have its returned function wrapped in useCallback?

### ISSUE THREAD

**Issue by tmdesigned** [juliencrn/usehooks.ts#27]
In useIsMounted, the function returns `() => isMounted.current`. Then in the usage example, when this function is invoked in a useEffect, the eslint disable flag `// eslint-disable-next-line react-hooks/exhaustive-deps` is used as it would otherwise warn that `isMounted` should be included (which would cause a loop as it changes on every render).

Instead, should the useIsMounted hook not wrap the return function in a useCallback? i.e. `return useCallback(() => mounted.current, []);` ?

This seems to work well on my project.

**Comment by juliencrn** [comment]
Hi @tmdesigned 👋
Indeed, you're right, good catch, thanks!
I've just fixed it here 2426bda020f47fbad630785e30d66adc7963bbe1
