### ISSUE TITLE
Any ways to use this directly from NPM Registery?

### ISSUE THREAD

**Issue by strange2x** [juliencrn/usehooks.ts#30]
Hey,

Nice work on this man. I would really like to use this in ongoing projects.. Any way to use this in an ongoing projects? Like using this directly from npmjs?

Thanks.

**Comment by bclermont** [comment]
duplicated of #26

**Comment by strange2x** [comment]
> 
> 
> duplicated of #26

oh sorry.. Thanks

**Comment by juliencrn** [comment]
Thanks @strange2x and @bclermont 

It's coming soon, I'm working on.
