### ISSUE TITLE
Question: How to test `useLocalStorage`

### ISSUE THREAD

**Issue by gmukul01** [juliencrn/usehooks.ts#33]
Actually  I am using `useLocalStorage` and writing unit tests around it and I am getting below error. I am using `Jest` & `react-testing-library`.

```
/node_modules/react-dom/cjs/react-dom.development.js:3905
      var evt = document.createEvent('Event');
                         ^

TypeError: Cannot read property 'createEvent' of null
```

**Comment by juliencrn** [comment]
Hi @gmukul01,

I haven't tested this yet, if you have found how to test it, a contribution is welcome :)
