### ISSUE TITLE
Possible Addition: useMap

### ISSUE THREAD

**Issue by jeanlucmongrain** [juliencrn/usehooks.ts#34]
https://medium.com/swlh/using-es6-map-with-react-state-hooks-800b91eedd5f

**Comment by jeanlucmongrain** [comment]
maybe:

```typescript
import React from "react";

interface updater<K, V> {
  (k: K, v: V): void;
}

function useMap<K, V>(): [Map<K, V>, updater<K, V>] {
  const [value, setter] = React.useState<Map<K, V>>(new Map<K, V>());
  const updater = function (k: K, v: V) {
    setter(new Map<K, V>(value.set(k, v)));
  };
  return [value, updater];
}

export default useMap;
```

**Comment by juliencrn** [comment]
Hi @jeanlucmongrain, nice idea! I will create a PR with this new hook, thanks!

Have you any examples of possible use cases?

**Comment by jeanlucmongrain** [comment]
Well, my use case is gone as I changed my API backend. But I'm sure it will be useful for me.

Map in typescript api is one of the worst. But, sometimes you really need them :)
