### ISSUE TITLE
[useLocalStorage] does not accept undefined in setter

### ISSUE THREAD

**Issue by valtism** [juliencrn/usehooks.ts#36]
When a state can be undefined, this hook does not support setting an undefined value.

In this example, you can set `state` to a string, but if you set it to `undefined` it will just return the initial value

```tsx
import useLocalStorage from "app/hooks/useLocalStorage"

export default function Test() {
  const [state, setState] = useLocalStorage<string | undefined>("someKey", "initial")

  return (
    <div>
      <button onClick={() => setState("new value")}>String</button>
      <button onClick={() => setState(undefined)}>undefined</button>
      {state}
    </div>
  )
}
```

This is because of this line in the code where if item does not exist we do not parse it.

```ts
return item ? (JSON.parse(item) as T) : initialValue
```

funnily enough `undefined` cannot be stored in localstorage, so it gets set as `"undefined"` and then causes a `JSON.parse` error that means we return the initial value anyway.

**Comment by valtism** [comment]
Because of this error I switched our prod to use [`useLocalSorageState`](https://github.com/astoilkov/use-local-storage-state) which handles this correctly. You might want to look at that for pointers on how to handle this case correctly.

**Comment by juliencrn** [comment]
Hi @valtism, thanks for this very useful feedback, I will update it.
